
flais:
  nam:
    federated-users-cleanup:
      cron: 0 0 0 * * *
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
