apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - onepassword.yml
  - service.yaml
commonLabels:
  app.kubernetes.io/name: flais-federated-temp-user-janitor
  app.kubernetes.io/instance: flais-federated-temp-user-janitor
  app.kubernetes.io/version: "latest"
  app.kubernetes.io/managed-by: GA
  app.kubernetes.io/component: operator
  app.kubernetes.io/part-of: fintlabs-application-infrastructure-services
  fintlabs.no/team: flais